language: node_js
node_js:
  - "8.9.4"
install:
  - npm install
env:
  - PORT=3000
script:
  - npm start test
  - npm start test.integration
  - npm start test.e2e
  - npm start build
notifications:
  email: false
